/*
 * chapter 7, exercise 7
 * Prime numbers can also be generated by an algorithm known as the Sieve of
 * Erastosthenes.The algorithm for this procedure is presented here.Write a program
 * that implements this algorithm. Have the program find all prime numbers up to n
 * = 150.What can you say about this algorithm as compared to the ones used in the
 * text for calculating prime numbers?
 * Sieve of Erastosthenes Algorithm
 * To Display All Prime Numbers Between 1 and n
 * Step 1: Define an array of integers P. Set all elements Pi to 0, 2 <= i <= n.
 * Step 2: Set i to 2.
 * Step 3: If i > n, the algorithm terminates.
 * Step 4: If Pi is 0, then i is prime.
 * Step 5: For all positive integer values of j, such that i x j ≤ n, set Pixj to 1.
 * Step 6: Add 1 to i and go to step 3.
 */

#include <stdio.h>

void sieveOfEratosthenes(int n)
{
    // Create a boolean array "isPrime[0..n]" and initialize all entries as true.
    // A value in isPrime[i] will finally be false if i is Not a prime, else true.
    int isPrime[n + 1];
    for (int i = 0; i <= n; i++)
    {
        isPrime[i] = 1;
    }

    // Start with the first prime number, 2.
    for (int p = 2; p * p <= n; p++)
    {
        // If isPrime[p] is not changed, then it is a prime.
        if (isPrime[p] == 1)
        {
            // Update all multiples of p.
            for (int i = p * p; i <= n; i += p)
            {
                isPrime[i] = 0;
            }
        }
    }

    // Print prime numbers.
    printf("Prime numbers up to %d are:\n", n);
    for (int i = 2; i <= n; i++)
    {
        if (isPrime[i])
        {
            printf("%d ", i);
        }
    }
}

int main(void)
{
    int n = 150;
    sieveOfEratosthenes(n);

    return 0;
}
